module.exports = {
  locals: {
    profile: {
      tradeName: 'My Company',
      firstName: 'Patrick',
      lastName: 'POTÉ',
      address: '3 rue du roseau',
      zip: '12345',
      city: 'Corneville',
      siret: 'XXX XXX XXX',
      apeCode: 'XXXX YY',
      taxId: 'XXYYZZAABB',
      phone: '+33 X XX XX XX XX',
      email: 'XXXXXX@XXXX.XX',
      rib: 'XXXXX XXXXX XXXXX XXXX XX',
      iban: 'FRXX XXXX XXX XXX XXX',
      bic: 'XXXXXXXX',
    },
    client: {
      name: 'Paul SOUBOTA toto tata tutu tott tuo tnohes tahoseut hasoe',
      address: '13 rue du port',
      zip: '67890',
      city: 'Mangelle',
      country: 'France',
    },
    document: {
      type: 'quotation',
      createdAt: '01/01/2019',
      expiresIn: 60,
      paymentDeadlineAt: '01/01/2019',
      items: [
        {designation: 'item a', quantity: 1, unitPrice: 33200, amount: 33200},
        {designation: 'item b', quantity: 2, unitPrice: 13350.4, amount: 33300.8},
        {
          designation:
            'item very very very very very very very very very very very very very very very very very very very very very very long',
          quantity: 2,
          unitPrice: 150.4,
          amount: 300.8,
        },
      ],
      number: 'F-1908-3923428',
      invoiceNumber: 40,
      rate: 200,
      rateUnit: 'hour',
      taxRate: 20,
      conditions: 'Condition A\nCondition B',
      totalHT: 100,
      totalTVA: 20,
      totalTTC: 120,
    },
  },
}
